In [2]:
from __future__ import print_function, division
import numpy as np

In [39]:
dataset = np.genfromtxt('data2.csv', delimiter = ',')
x = dataset[:, :-1]
y = dataset[:, -1]

In [4]:
z = dataset[:,0]
print(dataset)
print('----------------------------------------')
print(z)
(m,n) = dataset.shape
print('m = ',m)
print('n = ',n)
print(x)
print(y)
print(x.shape)
print(y.shape)
print(y.shape[0])

[[1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1. 1. 0. 1. 1.]
 [0. 1. 0. 1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 1. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0. 0. 1.]
 [0. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0. 0. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 0. 1. 1. 0. 1. 1.]
 [0. 0. 1. 1. 0. 1. 1. 1. 0.]
 [0. 0. 0. 1. 0. 1. 1. 1. 0.]
 [1. 1. 1. 0. 1. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1. 0. 1. 1. 1.]]
----------------------------------------
[1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
m =  24
n =  9
[[1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 

In [5]:
def total_entropy(data):
    (m,n) = data.shape
    y = data[:,-1]
    n_ = np.count_nonzero(y)
    n__ = m-n_
    p_ = n_/m
    p__ = n__/m
    if p_==0 or p__==0:
        return 0
    else:
        return(-(p_*np.log2(p_) + p__*np.log2(p__)))

In [6]:
print(total_entropy(dataset))

0.9544340029249649


In [7]:
def calc_att_entropy(data, i, y):
    (m,n) = data.shape
    A = data[:,i]
    (a_01,a_00,a_11,a_10) = (0,0,0,0)
    for i in range(m):
        if A[i]==0:
            if y[i]==1:
                a_01 = a_01 + 1
            else:
                a_00 = a_00 + 1
        if A[i]==1:
            if y[i]==1:
                a_11 = a_11 + 1
            else:
                a_10 = a_10 + 1
                
    if a_01+a_00==0:
        p_01 = 0
        p_00 = 0
    else:
        p_01 = a_01/(a_01+a_00)
        p_00 = a_00/(a_01+a_00)
        
    if a_11+a_10==0:
        p_11 = 0
        p_10 = 0
    else:
        p_11 = a_11/(a_11+a_10)
        p_10 = a_10/(a_11+a_10)
    
    #p_01 = a_01/(a_01+a_00)
    #p_00 = a_00/(a_01+a_00)
    #p_11 = a_11/(a_11+a_10)
    #p_10 = a_10/(a_11+a_10)
    
    if p_01==0 or p_00==0:
        E0 = 0
    else:
        E0 = (p_01*np.log2(p_01) + p_00*np.log2(p_00))
    if p_11==0 or p_10==0:
        E1 = 0
    else:
        E1 = (p_11*np.log2(p_11) + p_10*np.log2(p_10))
            
        
    #E0 = (p_01*np.log2(p_01) + p_00*np.log2(p_00))
    #E1 = (p_11*np.log2(p_11) + p_10*np.log2(p_10))
    
    E0 = (a_01+a_00)*E0
    E1 = (a_11+a_10)*E1
    
    return(-(E0+E1)/m)
                

In [8]:
def best_splitter(data):
    E_i = total_entropy(data)
    (m,n) = data.shape
    x = data[:,:-1]
    y = data[:,-1]
    list_entropy = np.zeros(n-1)
    
    for i in range(n-1):
        list_entropy[i] = calc_att_entropy(data, i, y)
    #return list_entropy, np.argmin(list_entropy)
    return np.argmin(list_entropy)
        

In [9]:
print(best_splitter(dataset))

1


In [10]:
#d1 = dataset[dataset[:,1]>0]
#d1_=dataset[dataset[:,1]==0]
#print(d1)
#print('-----------------------------------')
#print(d1_)
#print(d1.shape)
#print(d1_.shape)

In [11]:
#print(best_splitter(d1_))

In [12]:
#print(best_splitter(d1))

In [13]:
# d2 = d1[d1[:,0]>0]
# d2_=d1[d1[:,0]==0]
# print(d2)
# print('-----------------------------------')
# print(d2_)
# print(d2.shape)
# print(d2_.shape)

In [14]:
#print(best_splitter(d2_))

In [15]:
#print(best_splitter(d2))

In [16]:
#d3 = d2_[d2_[:,2]>0]
#d3_=d2_[d2_[:,2]==0]
#print(d3)
#print('-----------------------------------')
#print(d3_)
#print(d3.shape)
#print(d3_.shape)

In [17]:
#print(best_splitter(d3_))

In [18]:
#print(best_splitter(d3))

In [19]:
#d4 = d3[d3[:,6]>0]
#d4_=d3[d3[:,6]==0]
#print(d4)
#print('-----------------------------------')
#print(d4_)
#print(d4.shape)
#print(d4_.shape)

In [20]:
#print(best_splitter(d4))

In [21]:
#print(best_splitter(d4_))

In [22]:
class node:
    def __init__(self, value = None):
        self.val = value
        self.left_child = None
        self.right_child = None
         
# class tree:
#     def __init__(self, value = None):
#         self.root = node(value)
        
#     def build(self, data, cur_node):
#         if total_entropy(data) == 0:
#             if data[:,-1][0] == 0:
#                 cur_node

In [23]:
bst = node()

In [24]:
def build_tree(data, bst):
    if total_entropy(data) == 0:
        if data[:,-1][0] == 0:
            if bst == None:
                bst = node('N')
            else:   
                bst.val = 'N'
            print(bst.val)
        else:
            if bst == None:
                bst = node('Y')
            else: 
                bst.val = 'Y'
            print(bst.val)       
    else:
        i = best_splitter(data)
        if bst == None:
            bst = node(i)
        else:
            bst.val = i
        print(bst.val)
        bst.left_child = node()
        build_tree(data[data[:,i]==0], bst.left_child)
        bst.right_child = node()
        build_tree(data[data[:,i]>0], bst.right_child) 

In [25]:
build_tree(dataset, bst)

1
N
0
2
N
6
Y
N
Y


In [26]:
print(bst.__dict__)
print(bst.left_child.val)


{'left_child': <__main__.node instance at 0x7fb4080f1488>, 'right_child': <__main__.node instance at 0x7fb4080f14d0>, 'val': 1}
N


In [27]:
def printtree(Treenode):
    if Treenode.left_child != None:
        printtree (Treenode.left_child)
    print (Treenode.val, end=' ')
    if Treenode.right_child != None:
        printtree (Treenode.right_child)

In [28]:
printtree(bst)

N 1 N 2 Y 6 N 0 Y 

In [32]:
testset = np.genfromtxt('test2.csv', delimiter = ',')

In [40]:
print(testset)
print(testset.shape)
print(testset.shape[0])

[[0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0.]]
(4, 8)
4


In [41]:
def give_result(sample, bst):
    if bst.val == 'Y':
        print('1')
        return
    if bst.val == 'N':
        print('0')
        return
    if sample[bst.val] == 0:
        give_result(sample, bst.left_child)
    else:
        give_result(sample, bst.right_child)

In [37]:
def test_tree(testset, bst):
    
    for i in range(testset.shape[0]):
        give_result(testset[i], bst) 

In [38]:
test_tree(testset, bst)

0
0
1
1
