In [1]:
from __future__ import print_function, division
import numpy as np

In [2]:
dataset = np.genfromtxt('data4.csv', delimiter = ',')
x = dataset[:, :-1]
y = dataset[:, -1]

In [35]:
z = dataset[:,0]
print(dataset)
print('----------------------------------------')
print(z)
(m,n) = dataset.shape
print('m = ',m)
print('n = ',n)
print(x)
print(y)
print(x.shape)
print(y.shape)
print(y.shape[0])
print(y[0])

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [5.  2.  3.5 1.  1. ]
 [5.9 3.  4.2 1.5 1. ]
 [6.  2.2 4.  1.  1. ]
 [6.1 2.9 4.7 1.4 1. ]
 [5.6 2.9 3.6 1.3 1. ]
 [6.7 3.1 4.4 1.4 1. ]
 [5.6 3.  4.5 1.5 1. ]
 [5.8 2.7 4.1 1.  1. ]
 [6.2 2.2 4.5 1.5 1. ]
 [5.6 2.5 3

In [4]:
testset = np.genfromtxt('test4.csv', delimiter = ',')

In [5]:
print(testset)
print(testset.shape)
print(testset.shape[0])
print(testset[0])
print(testset[0,:])
print(testset[0,:].shape[0])
print(testset[0,:][0])

[[4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]]
(26, 4)
26
[4.9 3.1 1.5 0.1]
[4.9 3.1 1.5 0.1]
4
4.9


In [6]:
def distance(test_row, x, m):
    dist = 0
    for i in range(x.shape[1]):
        dist = dist + np.square(x[m][i]-test_row[i])
    dist = np.sqrt(dist)
    return dist
    

In [7]:
print(distance(testset[3], x, 5))

1.0099504938362076


In [30]:
l = np.empty([x.shape[0],2])
for i in range(x.shape[0]):
    l[i][0] = distance(testset[0], x, i)
    l[i][1] = i
    print(distance(testset[0], x, i))
print(l)    
print(len(l))
print(l[0][0])
print('----------------------------------------------')
print(l[0:5,:])
print(l[0:5, :].shape)

0.4690415759823426
0.17320508075688784
0.31622776601683805
0.3162277660168386
0.529150262212918
1.0099504938362076
0.4795831523312723
0.3316624790355397
0.5567764362830023
0.0
0.7874007874011811
0.3464101615137755
0.17320508075688812
0.7280109889280523
1.3114877048603997
1.5556349186104046
1.0099504938362076
0.4999999999999996
1.0999999999999996
0.7549834435270746
0.6244997998398397
0.6999999999999998
0.7745966692414836
0.5291502622129177
0.5196152422706631
0.19999999999999993
0.4472135954999578
0.5099019513592783
0.44721359549995776
0.26457513110645925
0.1732050807568881
0.6557438524302001
1.0440306508910546
1.260952021291849
2.4556058315617353
3.2031234756093934
3.0133038346638727
3.661966684720111
2.5258661880630173
3.6523964735499352
3.385262175962151
2.922327839240491
3.6687872655688283
2.758622844826744
3.845776904605882
3.036445290137795
3.97994974842648
3.602776706930364
3.4014702703389896
3.605551275463989
4.034848200366402
4.249705872175156
3.4942810419312296
2.38746727726266

In [26]:
l = l[l[:,0].argsort()]
print(l)
print(l[0:5,:])

[[ 0.          9.        ]
 [ 0.17320508  1.        ]
 [ 0.17320508 30.        ]
 [ 0.17320508 12.        ]
 [ 0.2        25.        ]
 [ 0.26457513 29.        ]
 [ 0.31622777  2.        ]
 [ 0.31622777  3.        ]
 [ 0.33166248  7.        ]
 [ 0.34641016 11.        ]
 [ 0.4472136  28.        ]
 [ 0.4472136  26.        ]
 [ 0.46904158  0.        ]
 [ 0.47958315  6.        ]
 [ 0.5        17.        ]
 [ 0.50990195 27.        ]
 [ 0.51961524 24.        ]
 [ 0.52915026 23.        ]
 [ 0.52915026  4.        ]
 [ 0.55677644  8.        ]
 [ 0.6244998  20.        ]
 [ 0.65574385 31.        ]
 [ 0.7        21.        ]
 [ 0.72801099 13.        ]
 [ 0.75498344 19.        ]
 [ 0.77459667 22.        ]
 [ 0.78740079 10.        ]
 [ 1.00995049 16.        ]
 [ 1.00995049  5.        ]
 [ 1.04403065 32.        ]
 [ 1.1        18.        ]
 [ 1.26095202 33.        ]
 [ 1.3114877  14.        ]
 [ 1.55563492 15.        ]
 [ 1.91049732 72.        ]
 [ 2.16794834 67.        ]
 [ 2.38746728 53.        ]
 

In [27]:
def give_list(test_row, x):
    l = np.empty([x.shape[0],2])
    for i in range(x.shape[0]):
        l[i][0] = distance(test_row, x, i)
        l[i][1] = i
    l = l[l[:,0].argsort()] 
    return l[0:5, :]

In [47]:
def give_majority(l, y):
    m = l.shape[0]
    n_zero = 0
    n_one = 0
    for i in range(m):
        if y[int(l[i][1])]==0:
            n_zero = n_zero + 1
        else:
            n_one = n_one + 1
    if n_one > n_zero:
        return 1
    else:
        return 0

In [55]:
p = give_list(testset[25], x)
print(p)
print(give_majority(p, y))

[[ 0.38729833 63.        ]
 [ 0.50990195 68.        ]
 [ 0.52915026 54.        ]
 [ 0.53851648 43.        ]
 [ 0.54772256 38.        ]]
1


In [49]:
def check_testset(testset, x, y):
    for i in range(testset.shape[0]):
        l = give_list(testset[i], x)
        print(give_majority(l, y))
        

In [50]:
check_testset(testset, x, y)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
