In [1]:
from __future__ import print_function, division
import numpy as np

In [2]:
dataset = np.genfromtxt('data7.csv', delimiter = ',')

In [3]:
x = dataset

In [4]:
print(x.shape)
print(x)
(m,n) = x.shape
print('m = ',m)
print('n = ',n)

(20, 8)
[[1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1. 1. 0. 0.]
 [1. 1. 1. 0. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 0.]
 [1. 0. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 1. 1. 1. 0. 1.]
 [1. 0. 0. 1. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 0. 1. 1. 0. 1.]]
m =  20
n =  8


In [14]:
#def dist(x, y):
    dist = np.square(x - y)
    dist = np.sqrt(dist)
    #return dist

In [21]:
def dist(x, y):
    return np.linalg.norm(x-y)
print(np.random.randint(0,m-1, size = 2))

[12  8]


In [22]:
print(dist(x[18],x[19]))

2.0


In [23]:
prototypes = x[np.random.randint(0, m - 1, size = 2)]
print(prototypes)
sum1 = np.zeros((1,8))
sum1 = sum1 + x[0]
print(sum1/m)

[[1. 1. 1. 0. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0.]]
[[0.05 0.05 0.05 0.05 0.05 0.05 0.   0.05]]


In [29]:
cents = []
cent = np.zeros((2,8))
for i in range(2):
    cent[i] = x[np.random.randint(0, m - 1)]
print(cent)
cents.append(cent)
print(cents)
label = np.zeros((m, 1))
print(label)

[[1. 0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0. 0.]]
[array([[1., 0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 0., 0.]])]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [33]:
for i in range(10):
    for j in range(m):
        d1 = dist(x[j], cent[0])
        d2 = dist(x[j], cent[1])
        if d1<d2:
            label[j][0] = 1
        else:
            label[j][0] = 2
    count1 = 0
    count2 = 0
    sum1 = np.zeros((1,8))
    sum2 = np.zeros((1,8))
    for k in range(m):
        if(label[k][0] == 1):
            sum1 = sum1 + x[k]
            count1 = count1 + 1
        else:
            sum2 = sum2 + x[k]
            count2 = count2 + 1
    cent[0] = sum1/count1
    cent[1] = sum2/count2
    #print(cent)
    #print('---')
print(label)
print(label[0])
print(label[0][0])

[[2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [2.]]
[2.]
2.0
