In [1]:
from __future__ import print_function, division
import numpy as np

In [2]:
dataset = np.genfromtxt('data3.csv', delimiter = ',')
x = dataset[:, :-1]
y = dataset[:, -1]

In [3]:
z = dataset[:,0]
print(dataset)
print('----------------------------------------')
print(z)
(m,n) = dataset.shape
print('m = ',m)
print('n = ',n)
print(x)
print(y)
print(x.shape)
print(y.shape)
print(y.shape[0])

[[1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 1. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 1. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 0. 1. 1. 0. 1. 1.]]
----------------------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 0.]
m =  20
n =  9
[[1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1. 1. 0. 0.]
 [1. 1. 1. 0. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 

In [28]:
def p_y(val, y):
    m = y.shape[0]
    n = np.count_nonzero(y)
    n_ = m-n
    if val == 0:
        return (n_+2)
    else:
        return (n+2)

In [29]:
def pabs_y(val, y):
    m = y.shape[0]
    n = np.count_nonzero(y)
    n_ = m-n
    if val == 0:
        return (n_)/m
    else:
        return (n)/m

In [30]:
print(pabs_y(0,y))
print(pabs_y(1,y))

0.35
0.65


In [31]:
def p_a_int_y(a, y, a_val, y_val):
    m = a.shape[0]
    n_int = 1
    for i in range(m):
        if a[i] == a_val and y[i] == y_val:
            n_int = n_int + 1
    return n_int       

In [32]:
#here i stands for attribute index
#i varies from 0 to 7
def p_att(x, y, i, att_val, y_val):
    (m,n) = x.shape
    a = x[:,i]
    n_a1 = np.count_nonzero(a)
    n_a0 = m - n_a1
    if att_val == 0:
        if y_val == 0:
            #print(p_a_int_y(a, y, 0, 0)/p_y(0, y))
            return p_a_int_y(a, y, 0, 0)/p_y(0, y)
        if y_val == 1:
            #print(p_a_int_y(a, y, 0, 1)/p_y(1, y))
            return p_a_int_y(a, y, 0, 1)/p_y(1, y)
    elif att_val == 1:
        if y_val == 0:
            #print(p_a_int_y(a, y, 1, 0)/p_y(0, y))
            return p_a_int_y(a, y, 1, 0)/p_y(0, y)
        if y_val == 1:
            #print(p_a_int_y(a, y, 1, 1)/p_y(1, y))
            return p_a_int_y(a, y, 1, 1)/p_y(1, y)

In [33]:
p_att(x,y,0,0,0)

0.1111111111111111

In [34]:
p_att(x,y,0,1,0)

0.8888888888888888

In [35]:
testset = np.genfromtxt('test3.csv', delimiter = ',')

In [36]:
print(testset)
print(testset.shape)
print(testset.shape[0])
print(testset[0,:])
print(testset[0,:].shape[0])
print(testset[0,:][0])

[[0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0.]]
(4, 8)
4
[0. 1. 1. 1. 1. 1. 1. 1.]
8
0.0


In [37]:
def give_prob(x_row, y_val, x_data, y_data):
    v_map = pabs_y(y_val,y)
    for i in range(x_row.shape[0]):
        v_map = v_map * p_att(x_data, y_data, i, x_row[i], y_val)
    return v_map    

In [38]:
def predict_prob(testset, x_data, y_data):
    m = testset.shape[0]
    for i in range(m):
        a = give_prob(testset[i,:], 0, x_data, y_data)
        a_ = give_prob(testset[i,:], 1, x_data, y_data)
        print(a, a_)
        if a>a_:
            print(0)
        else:
            print(1)

In [39]:
predict_prob(testset, x , y)

0.00159856078236 0.00240514423045
1
2.43921017817e-05 9.39509465021e-06
0
3.90273628507e-06 0.0171867598134
1
3.12218902806e-05 0.0257801397202
1
