In [1]:
from __future__ import print_function, division
import numpy as np

In [2]:
dataset = np.genfromtxt('data6.csv', delimiter = ',')
x = dataset[:, :-1]
y = dataset[:, -1]

In [3]:
z = dataset[:,0]
print(dataset)
print('----------------------------------------')
print(z)
(m,n) = dataset.shape
print('m = ',m)
print('n = ',n)
print(x)
print(y)
print(x.shape)
print(y.shape)
print(y.shape[0])

[[1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 1. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 1. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 0. 1. 1. 0. 1. 1.]]
----------------------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 0.]
m =  20
n =  9
[[1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1. 1. 0. 0.]
 [1. 1. 1. 0. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 

In [4]:
testset = np.genfromtxt('test6.csv', delimiter = ',')
test_ = np.insert(testset, 0, 1, axis = 1)

In [5]:
print(testset)
print(testset.shape)
print(testset.shape[0])
print(test_)

[[0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0.]]
(4, 8)
4
[[1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 0. 0. 0.]]


In [7]:
x_ = np.insert(x, 0, 1, axis = 1)
print(x_)
print(x)
print(x.shape)
print(x_.shape)

[[1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 1. 0. 0. 1.]
 [1. 1. 1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 0. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 0. 0. 1. 1. 1. 0. 1.]
 [1. 1. 0. 0. 1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 0. 1. 1. 0. 1.]]
[[1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1. 1. 0. 0.]
 [1. 1. 1. 0. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 0.]
 [1. 0. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 0. 1. 0. 1. 0

In [8]:
x_[1]

array([1., 1., 1., 1., 1., 1., 1., 0., 0.])

In [9]:
w = np.random.randn(x_.shape[1],)
#w = np.random.randn(8,)
print(w)
w.shape

[ 0.439172    2.01428871 -0.70598441 -0.58888501  0.63823638  0.49625542
  1.0353197   2.09107019 -1.98567902]


(9,)

In [10]:
y1 = np.dot(w, x_[0])
print(y1)
print(np.sum(w)-w[7] - w[8])
sums = np.zeros(x.shape[1],)
print(sums)
print(range(x.shape[0]))

1.3427237830027907
3.328402798917823
[0. 0. 0. 0. 0. 0. 0. 0.]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [11]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [12]:
def sig_der(x):
    return(sigmoid(x)*(1-sigmoid(x)))

In [13]:
def give_sum(w, x):
    sums = np.zeros(x.shape[0],)
    for i in range(x.shape[0]):
        sums[i] = np.dot(w, x[i]) 
    return sums

In [14]:
def give_class(sig):
    for i in range(sig.shape[0]):
        if sig[i] > 0.5:
            sig[i] = 1
        else:
            sig[i] = 0
    return sig        

In [15]:
ex = give_sum(w, x_)
print(ex)
ex1 = sigmoid(ex)
print(ex1)
print(sigmoid(ex[0]))
print(y)

[ 1.34272378  3.3284028   3.43379398  0.30740408  2.2930831   0.70448741
  1.93160879  2.69016642 -0.3308323   1.65484672 -0.67156493  1.31411408
  2.04870819 -1.70688463  1.43535337  2.6375932   4.23240797  0.27879438
  4.13977838 -1.30980131]
[0.79293751 0.96539044 0.96874415 0.5762515  0.90830256 0.66918194
 0.87342738 0.93644389 0.41803813 0.83954502 0.33814652 0.78820078
 0.88581702 0.15356823 0.80773406 0.93324217 0.98569035 0.56925063
 0.98432329 0.21252009]
0.7929375097136824
[1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1.]


In [16]:
#y_pred is the sigmoid as above
def give_error(y, y_pred):
    error = 0
    for i in range(y.shape[0]):
        error = error + (y[i] - y_pred[i])*(y[i] - y_pred[i])
    return 0.5*error

In [17]:
print(give_error(ex1, y))

4.332420053586468


In [18]:
def dE_dw(x_, y, y_pred, w):
    grad = np.zeros(w.shape[0],)
    for i in range(w.shape[0]):
        q = 0
        for j in range(x.shape[0]):
            q = q - (y[j] - y_pred[j])*y_pred[j]*(1 - y_pred[j])*x_[j][i]
        grad[i] = q
    return grad

In [19]:
print(dE_dw(x_, y, ex1, w))

[-4.89232252e-01  4.16846872e-02 -6.66062630e-01 -7.83277458e-01
 -1.17229241e-01 -6.28576197e-01  7.19296957e-04  5.84246204e-02
 -3.14061637e-01]


In [20]:
print(w)
print(dE_dw(x_, y, ex1, w))
print( w - 0.1*dE_dw(x_, y, ex1, w))

[ 0.439172    2.01428871 -0.70598441 -0.58888501  0.63823638  0.49625542
  1.0353197   2.09107019 -1.98567902]
[-4.89232252e-01  4.16846872e-02 -6.66062630e-01 -7.83277458e-01
 -1.17229241e-01 -6.28576197e-01  7.19296957e-04  5.84246204e-02
 -3.14061637e-01]
[ 0.48809522  2.01012025 -0.63937814 -0.51055726  0.6499593   0.55911304
  1.03524777  2.08522773 -1.95427285]


In [21]:
for n in range(1000):
    sums = give_sum(w, x_)
    y_pred = sigmoid(sums)
    print('error:')
    print(give_error(y, y_pred))
    grad = dE_dw(x_, y, y_pred, w)
    w = w - 0.1*grad

error:
4.332420053586468
error:
4.157972174562678
error:
4.009868647364206
error:
3.888626294520728
error:
3.792283517797751
error:
3.7172789433547724
error:
3.659467216735375
error:
3.6149171390818524
error:
3.5803247467806663
error:
3.55310793527169
error:
3.5313302188321947
error:
3.5135683791638823
error:
3.498783070310425
error:
3.4862132209018566
error:
3.4752966241912566
error:
3.465612530257025
error:
3.456840854872834
error:
3.4487333210792963
error:
3.4410929623507416
error:
3.433759419135711
error:
3.4265982301284983
error:
3.4194928704010104
error:
3.4123386693727857
error:
3.4050380002316802
error:
3.3974963061816674
error:
3.3896186445980705
error:
3.3813065063470877
error:
3.3724547168636088
error:
3.362948256943636
error:
3.3526588612335653
error:
3.3414412668271627
error:
3.3291289993112736
error:
3.3155296068790308
error:
3.300419296037906
error:
3.2835370017744707
error:
3.2645780653836045
error:
3.243187928570326
error:
3.2189566252990645
error:
3.191415405639033
er

error:
0.10468074248070627
error:
0.104408478455301
error:
0.10413772501121546
error:
0.1038684690174302
error:
0.10360069749651532
error:
0.10333439762241185
error:
0.1030695567182508
error:
0.10280616225420927
error:
0.10254420184540265
error:
0.1022836632498124
error:
0.1020245343662486
error:
0.10176680323234616
error:
0.10151045802259569
error:
0.10125548704640609
error:
0.10100187874619979
error:
0.10074962169553967
error:
0.10049870459728705
error:
0.10024911628178979
error:
0.10000084570510087
error:
0.09975388194722537
error:
0.09950821421039713
error:
0.09926383181738307
error:
0.09902072420981521
error:
0.0987788809465502
error:
0.09853829170205528
error:
0.09829894626482037
error:
0.09806083453579605
error:
0.09782394652685653
error:
0.09758827235928748
error:
0.09735380226229844
error:
0.09712052657155834
error:
0.0968884357277553
error:
0.09665752027517881
error:
0.0964277708603249
error:
0.09619917823052294
error:
0.0959717332325848
error:
0.09574542681147502
error:
0.09

error:
0.04918275993415864
error:
0.04912515584904841
error:
0.04906768556514912
error:
0.04901034860742764
error:
0.04895314450315394
error:
0.048896072781886714
error:
0.04883913297545939
error:
0.04878232461796573
error:
0.04872564724574625
error:
0.04866910039737429
error:
0.048612683613642356
error:
0.04855639643754828
error:
0.04850023841428176
error:
0.04844420909121129
error:
0.0483883080178703
error:
0.04833253474594431
error:
0.04827688882925765
error:
0.048221369823760594
error:
0.04816597728751624
error:
0.0481107107806877
error:
0.048055569865525484
error:
0.048000554106354884
error:
0.047945663069563216
error:
0.047890896323587506
error:
0.04783625343890204
error:
0.04778173398800634
error:
0.04772733754541257
error:
0.04767306368763386
error:
0.04761891199317195
error:
0.047564882042505495
error:
0.04751097341807819
error:
0.047457185704286864
error:
0.047403518487470056
error:
0.04734997135589648
error:
0.047296543899753095
error:
0.04724323571113413
error:
0.0471900463

In [22]:
print(w)

[ 0.40860503 -1.64772492  3.47891099  3.49420292 -1.73820416  1.55339938
 -1.71621241 -3.45224515 -2.38565356]


In [23]:
print(w)

[ 0.40860503 -1.64772492  3.47891099  3.49420292 -1.73820416  1.55339938
 -1.71621241 -3.45224515 -2.38565356]


In [24]:
def test(testset, weights):
    sums = give_sum(weights, testset)
    y_pred = sigmoid(sums)
    #print(y_pred)
    return(give_class(y_pred))

In [26]:
print(test(test_,w))
res = test(test_,w)
print(res.shape)
print(y)
print(test(x_,w))

[0. 0. 1. 1.]
(4,)
[1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1.]
[1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1.]
